int  __attribute__((weak)) bbs04_clear (void) { return 0; }
int  __attribute__((weak)) bbs04_get_joinseq (void) { return 0; }
int  __attribute__((weak)) bbs04_get_joinstart (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_entry_export (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_entry_free (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_entry_get_size (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_entry_import (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_entry_init (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_entry_to_string (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_export (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_free (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_get (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_import (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_init (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_insert (void) { return 0; }
int  __attribute__((weak)) bbs04_gml_remove (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_copy (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_export (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_free (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_get_size (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_import (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_init (void) { return 0; }
int  __attribute__((weak)) bbs04_grp_key_to_string (void) { return 0; }
int  __attribute__((weak)) bbs04_init (void) { return 0; }
int  __attribute__((weak)) bbs04_join_mem (void) { return 0; }
int  __attribute__((weak)) bbs04_join_mgr (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_copy (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_export (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_free (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_get_size (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_import (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_init (void) { return 0; }
int  __attribute__((weak)) bbs04_mem_key_to_string (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_copy (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_export (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_free (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_get_size (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_import (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_init (void) { return 0; }
int  __attribute__((weak)) bbs04_mgr_key_to_string (void) { return 0; }
int  __attribute__((weak)) bbs04_open (void) { return 0; }
int  __attribute__((weak)) bbs04_setup (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_copy (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_export (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_free (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_get_size (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_import (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_init (void) { return 0; }
int  __attribute__((weak)) bbs04_signature_to_string (void) { return 0; }
int  __attribute__((weak)) bbs04_sign (void) { return 0; }
int  __attribute__((weak)) bbs04_verify (void) { return 0; }
int  __attribute__((weak)) dl21_clear (void) { return 0; }
int  __attribute__((weak)) dl21_get_joinseq (void) { return 0; }
int  __attribute__((weak)) dl21_get_joinstart (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_copy (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_export (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_free (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_get_size (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_import (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_init (void) { return 0; }
int  __attribute__((weak)) dl21_grp_key_to_string (void) { return 0; }
int  __attribute__((weak)) dl21_identify (void) { return 0; }
int  __attribute__((weak)) dl21_identity_cmp (void) { return 0; }
int  __attribute__((weak)) dl21_identity_copy (void) { return 0; }
int  __attribute__((weak)) dl21_identity_free (void) { return 0; }
int  __attribute__((weak)) dl21_identity_from_string (void) { return 0; }
int  __attribute__((weak)) dl21_identity_init (void) { return 0; }
int  __attribute__((weak)) dl21_identity_to_string (void) { return 0; }
int  __attribute__((weak)) dl21_init (void) { return 0; }
int  __attribute__((weak)) dl21_join_mem (void) { return 0; }
int  __attribute__((weak)) dl21_join_mgr (void) { return 0; }
int  __attribute__((weak)) dl21_link (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_copy (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_export (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_free (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_get_size (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_import (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_init (void) { return 0; }
int  __attribute__((weak)) dl21_mem_key_to_string (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_copy (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_export (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_free (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_get_size (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_import (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_init (void) { return 0; }
int  __attribute__((weak)) dl21_mgr_key_to_string (void) { return 0; }
int  __attribute__((weak)) dl21_proof_copy (void) { return 0; }
int  __attribute__((weak)) dl21_proof_export (void) { return 0; }
int  __attribute__((weak)) dl21_proof_free (void) { return 0; }
int  __attribute__((weak)) dl21_proof_get_size (void) { return 0; }
int  __attribute__((weak)) dl21_proof_import (void) { return 0; }
int  __attribute__((weak)) dl21_proof_init (void) { return 0; }
int  __attribute__((weak)) dl21_proof_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_clear (void) { return 0; }
int  __attribute__((weak)) dl21seq_get_joinseq (void) { return 0; }
int  __attribute__((weak)) dl21seq_get_joinstart (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_copy (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_export (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_free (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_get_size (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_import (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_grp_key_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_identify (void) { return 0; }
int  __attribute__((weak)) dl21seq_identity_cmp (void) { return 0; }
int  __attribute__((weak)) dl21seq_identity_copy (void) { return 0; }
int  __attribute__((weak)) dl21seq_identity_free (void) { return 0; }
int  __attribute__((weak)) dl21seq_identity_from_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_identity_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_identity_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_join_mem (void) { return 0; }
int  __attribute__((weak)) dl21seq_join_mgr (void) { return 0; }
int  __attribute__((weak)) dl21seq_link (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_copy (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_export (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_free (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_get_size (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_import (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_mem_key_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_copy (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_export (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_free (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_get_size (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_import (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_mgr_key_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_copy (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_export (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_free (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_get_size (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_import (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_proof_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_seqlink (void) { return 0; }
int  __attribute__((weak)) dl21seq_setup (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_copy (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_export (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_free (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_get_size (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_import (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_init (void) { return 0; }
int  __attribute__((weak)) dl21seq_signature_to_string (void) { return 0; }
int  __attribute__((weak)) dl21seq_sign (void) { return 0; }
int  __attribute__((weak)) dl21seq_verify_link (void) { return 0; }
int  __attribute__((weak)) dl21seq_verify_seqlink (void) { return 0; }
int  __attribute__((weak)) dl21seq_verify (void) { return 0; }
int  __attribute__((weak)) dl21_setup (void) { return 0; }
int  __attribute__((weak)) dl21_signature_copy (void) { return 0; }
int  __attribute__((weak)) dl21_signature_export (void) { return 0; }
int  __attribute__((weak)) dl21_signature_free (void) { return 0; }
int  __attribute__((weak)) dl21_signature_get_size (void) { return 0; }
int  __attribute__((weak)) dl21_signature_import (void) { return 0; }
int  __attribute__((weak)) dl21_signature_init (void) { return 0; }
int  __attribute__((weak)) dl21_signature_to_string (void) { return 0; }
int  __attribute__((weak)) dl21_sign (void) { return 0; }
int  __attribute__((weak)) dl21_verify_link (void) { return 0; }
int  __attribute__((weak)) dl21_verify (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_copy (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_export_prv (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_export_pub (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_export (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_free (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_get_size (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_import (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_init (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_random (void) { return 0; }
int  __attribute__((weak)) gl19_bld_key_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_copy (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_export (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_free (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_get_size (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_import (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_init (void) { return 0; }
int  __attribute__((weak)) gl19_blindsig_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_blind (void) { return 0; }
int  __attribute__((weak)) gl19_clear (void) { return 0; }
int  __attribute__((weak)) gl19_convert (void) { return 0; }
int  __attribute__((weak)) gl19_get_joinseq (void) { return 0; }
int  __attribute__((weak)) gl19_get_joinstart (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_copy (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_export (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_free (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_get_size (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_import (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_init (void) { return 0; }
int  __attribute__((weak)) gl19_grp_key_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_identity_cmp (void) { return 0; }
int  __attribute__((weak)) gl19_identity_copy (void) { return 0; }
int  __attribute__((weak)) gl19_identity_free (void) { return 0; }
int  __attribute__((weak)) gl19_identity_from_string (void) { return 0; }
int  __attribute__((weak)) gl19_identity_init (void) { return 0; }
int  __attribute__((weak)) gl19_identity_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_init (void) { return 0; }
int  __attribute__((weak)) gl19_join_mem (void) { return 0; }
int  __attribute__((weak)) gl19_join_mgr (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_copy (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_export (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_free (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_get_size (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_import (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_init (void) { return 0; }
int  __attribute__((weak)) gl19_mem_key_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_copy (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_export (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_free (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_get_size (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_import (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_init (void) { return 0; }
int  __attribute__((weak)) gl19_mgr_key_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_setup (void) { return 0; }
int  __attribute__((weak)) gl19_signature_copy (void) { return 0; }
int  __attribute__((weak)) gl19_signature_export (void) { return 0; }
int  __attribute__((weak)) gl19_signature_free (void) { return 0; }
int  __attribute__((weak)) gl19_signature_get_size (void) { return 0; }
int  __attribute__((weak)) gl19_signature_import (void) { return 0; }
int  __attribute__((weak)) gl19_signature_init (void) { return 0; }
int  __attribute__((weak)) gl19_signature_to_string (void) { return 0; }
int  __attribute__((weak)) gl19_sign (void) { return 0; }
int  __attribute__((weak)) gl19_unblind (void) { return 0; }
int  __attribute__((weak)) gl19_verify (void) { return 0; }
int  __attribute__((weak)) klap20_clear (void) { return 0; }
int  __attribute__((weak)) klap20_get_joinseq (void) { return 0; }
int  __attribute__((weak)) klap20_get_joinstart (void) { return 0; }
int  __attribute__((weak)) klap20_gml_entry_export (void) { return 0; }
int  __attribute__((weak)) klap20_gml_entry_free (void) { return 0; }
int  __attribute__((weak)) klap20_gml_entry_get_size (void) { return 0; }
int  __attribute__((weak)) klap20_gml_entry_import (void) { return 0; }
int  __attribute__((weak)) klap20_gml_entry_init (void) { return 0; }
int  __attribute__((weak)) klap20_gml_entry_to_string (void) { return 0; }
int  __attribute__((weak)) klap20_gml_export (void) { return 0; }
int  __attribute__((weak)) klap20_gml_free (void) { return 0; }
int  __attribute__((weak)) klap20_gml_get (void) { return 0; }
int  __attribute__((weak)) klap20_gml_import (void) { return 0; }
int  __attribute__((weak)) klap20_gml_init (void) { return 0; }
int  __attribute__((weak)) klap20_gml_insert (void) { return 0; }
int  __attribute__((weak)) klap20_gml_remove (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_copy (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_export (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_free (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_get_size (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_import (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_init (void) { return 0; }
int  __attribute__((weak)) klap20_grp_key_to_string (void) { return 0; }
int  __attribute__((weak)) klap20_init (void) { return 0; }
int  __attribute__((weak)) klap20_join_mem (void) { return 0; }
int  __attribute__((weak)) klap20_join_mgr (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_copy (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_export (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_free (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_get_size (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_import (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_init (void) { return 0; }
int  __attribute__((weak)) klap20_mem_key_to_string (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_copy (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_export (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_free (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_get_size (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_import (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_init (void) { return 0; }
int  __attribute__((weak)) klap20_mgr_key_to_string (void) { return 0; }
int  __attribute__((weak)) klap20_open_verify (void) { return 0; }
int  __attribute__((weak)) klap20_open (void) { return 0; }
int  __attribute__((weak)) klap20_proof_export (void) { return 0; }
int  __attribute__((weak)) klap20_proof_free (void) { return 0; }
int  __attribute__((weak)) klap20_proof_get_size (void) { return 0; }
int  __attribute__((weak)) klap20_proof_import (void) { return 0; }
int  __attribute__((weak)) klap20_proof_init (void) { return 0; }
int  __attribute__((weak)) klap20_proof_to_string (void) { return 0; }
int  __attribute__((weak)) klap20_setup (void) { return 0; }
int  __attribute__((weak)) klap20_signature_copy (void) { return 0; }
int  __attribute__((weak)) klap20_signature_export (void) { return 0; }
int  __attribute__((weak)) klap20_signature_free (void) { return 0; }
int  __attribute__((weak)) klap20_signature_get_size (void) { return 0; }
int  __attribute__((weak)) klap20_signature_import (void) { return 0; }
int  __attribute__((weak)) klap20_signature_init (void) { return 0; }
int  __attribute__((weak)) klap20_signature_to_string (void) { return 0; }
int  __attribute__((weak)) klap20_sign (void) { return 0; }
int  __attribute__((weak)) klap20_verify_batch (void) { return 0; }
int  __attribute__((weak)) klap20_verify (void) { return 0; }
int  __attribute__((weak)) ps16_clear (void) { return 0; }
int  __attribute__((weak)) ps16_get_joinseq (void) { return 0; }
int  __attribute__((weak)) ps16_get_joinstart (void) { return 0; }
int  __attribute__((weak)) ps16_gml_entry_export (void) { return 0; }
int  __attribute__((weak)) ps16_gml_entry_free (void) { return 0; }
int  __attribute__((weak)) ps16_gml_entry_get_size (void) { return 0; }
int  __attribute__((weak)) ps16_gml_entry_import (void) { return 0; }
int  __attribute__((weak)) ps16_gml_entry_init (void) { return 0; }
int  __attribute__((weak)) ps16_gml_entry_to_string (void) { return 0; }
int  __attribute__((weak)) ps16_gml_export (void) { return 0; }
int  __attribute__((weak)) ps16_gml_free (void) { return 0; }
int  __attribute__((weak)) ps16_gml_get (void) { return 0; }
int  __attribute__((weak)) ps16_gml_import (void) { return 0; }
int  __attribute__((weak)) ps16_gml_init (void) { return 0; }
int  __attribute__((weak)) ps16_gml_insert (void) { return 0; }
int  __attribute__((weak)) ps16_gml_remove (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_copy (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_export (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_free (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_get_size (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_import (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_init (void) { return 0; }
int  __attribute__((weak)) ps16_grp_key_to_string (void) { return 0; }
int  __attribute__((weak)) ps16_init (void) { return 0; }
int  __attribute__((weak)) ps16_join_mem (void) { return 0; }
int  __attribute__((weak)) ps16_join_mgr (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_copy (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_export (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_free (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_get_size (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_import (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_init (void) { return 0; }
int  __attribute__((weak)) ps16_mem_key_to_string (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_copy (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_export (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_free (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_get_size (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_import (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_init (void) { return 0; }
int  __attribute__((weak)) ps16_mgr_key_to_string (void) { return 0; }
int  __attribute__((weak)) ps16_open_verify (void) { return 0; }
int  __attribute__((weak)) ps16_open (void) { return 0; }
int  __attribute__((weak)) ps16_proof_export (void) { return 0; }
int  __attribute__((weak)) ps16_proof_free (void) { return 0; }
int  __attribute__((weak)) ps16_proof_get_size (void) { return 0; }
int  __attribute__((weak)) ps16_proof_import (void) { return 0; }
int  __attribute__((weak)) ps16_proof_init (void) { return 0; }
int  __attribute__((weak)) ps16_proof_to_string (void) { return 0; }
int  __attribute__((weak)) ps16_setup (void) { return 0; }
int  __attribute__((weak)) ps16_signature_copy (void) { return 0; }
int  __attribute__((weak)) ps16_signature_export (void) { return 0; }
int  __attribute__((weak)) ps16_signature_free (void) { return 0; }
int  __attribute__((weak)) ps16_signature_get_size (void) { return 0; }
int  __attribute__((weak)) ps16_signature_import (void) { return 0; }
int  __attribute__((weak)) ps16_signature_init (void) { return 0; }
int  __attribute__((weak)) ps16_signature_to_string (void) { return 0; }
int  __attribute__((weak)) ps16_sign (void) { return 0; }
int  __attribute__((weak)) ps16_verify (void) { return 0; }
